### ISSUE TITLE
Verify(10) command in SCSI compliance 2 reported as failure even thought it is mandatory

### ISSUE THREAD

**Issue by EthanDDN** [MicrosoftDocs/commercialization-public#329] opened 2018-09-06 17:43 UTC
Ran the windows HCK SCSI compliance test 2 on my company hardware platform. It reported failure for verify (10) support command even thought it is optional to support it.  This should be reported as "warning" instead of failure

According to the Microsoft's documentation for the test, "Optional commands are also tested. If a device supports the optional commands and the commands are found to be non-compliant, the test fails. If the device does not support optional commands, the test passes." So an optional command should be permitted to say that it is not supported.

**Comment by EliotSeattle** [comment] 2018-09-06 22:14
Duplicate of Issue #330

**Closed by EliotSeattle** 2018-09-06 22:14 UTC
Labels: HLK, duplicate
